export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT'
export const ADD_TODO = 'ADD_TODO'
export const ADD_TODOS = 'ADD_TODOS'
export const TOGGLE_SHOW_COMPLETED = 'TOGGLE_SHOW_COMPLETED'
export const TOGGLE_TODO = 'TOGGLE_TODO'
export const UPDATE_TODO = 'UPDATE_TODO'
export const UPDATE_TODOS = 'UPDATE_TODOS'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'

